/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classesDialogues;

import classes.Constants;
import classes.ServiceClass;
import classes.Transaction;
import services.database.DataManager;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import static services.database.DataManager.getClientsNames;
import static services.database.DataManager.rezultat;

/**
 *
 * @author marius
 */
public class AddTransaction extends javax.swing.JDialog {

    /**
     * Creates new form AddTransaction
     */
    public AddTransaction(java.awt.Frame parent, boolean modal,ServiceClass Service) {
        super(parent, modal);
        initComponents();
        jTransValue.setHorizontalAlignment(JTextField.RIGHT);
        jTransValue.setText("0.00 lei");
        jTransValue.setForeground(Color.GRAY);
        jTransValue.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            if (jTransValue.getText().equals("0.00 lei")) {
                jTransValue.setText("");
                jTransValue.setForeground(Color.BLACK);
            }
        }
        @Override
        public void focusLost(FocusEvent e) {
            if (jTransValue.getText().isEmpty()) {
                jTransValue.setForeground(Color.GRAY);
                jTransValue.setText("0.00 lei");
            }
        }
        });
        jTransDisc.setHorizontalAlignment(JTextField.RIGHT);
        jTransDisc.setText("0.00 %");
        jTransDisc.setForeground(Color.GRAY);
        jTransDisc.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            if (jTransDisc.getText().equals("0.00 %")) {
                jTransDisc.setText("");
                jTransDisc.setForeground(Color.BLACK);
            }
        }
        @Override
        public void focusLost(FocusEvent e) {
            if (jTransDisc.getText().isEmpty()) {
                jTransDisc.setForeground(Color.GRAY);
                jTransDisc.setText("0.00 %");
            }
        }
        });
        getClientsNames();
        try {
            while(rezultat.next())
            {
                    jTransClient.addItem(rezultat.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddTransaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public AddTransaction(java.awt.Frame parent, boolean modal,Transaction trans) {
        super(parent, modal);
        initComponents();
        jTransAdd.setText("Modifica");
        Calendar cal = Calendar.getInstance();
        cal.setTime(trans.getData());
        jTransDate.setSelectedDate(cal);
        jTransDisc.setText(String.valueOf(trans.getDiscount()));
        jTransValue.setText(String.valueOf(trans.getValue()));
        jTransDescr.setText(trans.getDescription());
        getClientsNames();
        int i=0,found=0;
        try {
            while(rezultat.next())
            {
                    jTransClient.addItem(rezultat.getString(1));
                    if(rezultat.getString(1).equals(trans.getClient())) 
                    {
                        jTransClient.setSelectedIndex(i);
                        found=1;
                    }
                    i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddTransaction.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(found ==0)
        {
            jTransClient.addItem(trans.getClient());
            jTransClient.setSelectedIndex(i);
        }
        for(i=0;i<jTransType.getItemCount();i++)
        {
            if(jTransType.getItemAt(i).equals(Constants.getType(trans.getType()))) {
                jTransType.setSelectedIndex(i);
                break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTransDate = new datechooser.beans.DateChooserCombo();
        jTransType = new javax.swing.JComboBox<>();
        jTransClient = new javax.swing.JComboBox<>();
        jTransDescr = new javax.swing.JTextField();
        jTransValue = new javax.swing.JTextField();
        jTransDisc = new javax.swing.JTextField();
        jTransAdd = new javax.swing.JButton();
        jTransCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 280));

        jLabel1.setText("Data :");

        jLabel2.setText("Descriere :");

        jLabel3.setText("Valoare :");

        jLabel5.setText("Discount :");

        jLabel6.setText("Tip : ");

        jLabel7.setText("Client :");

        jTransType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SALE", "REGISTER_INFLOW", "REGISTER_OUTFLOW", "PRODUCT_RETURN", "PRICE_CORRECTION", "SUPPLY", "CLIENT_DEPOSIT" }));
        jTransType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTransTypeActionPerformed(evt);
            }
        });

        jTransAdd.setText("Adauga");
        jTransAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTransAddActionPerformed(evt);
            }
        });

        jTransCancel.setText("Anuleaza");
        jTransCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTransCancelActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Adauga produs");

        jButton2.setText("Sterge produs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTransType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTransClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTransDescr)
                                .addComponent(jTransValue)
                                .addComponent(jTransDisc))
                            .addComponent(jTransDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jTransAdd)
                        .addGap(53, 53, 53)
                        .addComponent(jTransCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTransDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTransType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTransClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTransDescr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTransValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTransDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTransAdd)
                    .addComponent(jTransCancel))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTransCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTransCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jTransCancelActionPerformed

    private void jTransAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTransAddActionPerformed
        // TODO add your handling code here:
            Transaction trans = new Transaction();
            trans.setData(jTransDate.getSelectedDate().getTime());
            trans.setType(Constants.getType(jTransType.getSelectedItem().toString()));
            trans.setClient(jTransClient.getSelectedItem().toString());
            trans.setDescription(jTransDescr.getText());
            trans.setValue(Double.parseDouble(jTransValue.getText().replaceAll(" lei", "")));
            trans.setDiscount(Double.parseDouble(jTransDisc.getText().replaceAll(" %", "")));
        
        if(jTransAdd.getText().equals("Adauga") ) DataManager.addTransaction(trans);
        else DataManager.modifyTransaction(trans);
        this.dispose();
    }//GEN-LAST:event_jTransAddActionPerformed

    private void jTransTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTransTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTransTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddTransaction dialog = new AddTransaction(new javax.swing.JFrame(), true,new ServiceClass());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jTransAdd;
    private javax.swing.JButton jTransCancel;
    private javax.swing.JComboBox<String> jTransClient;
    private datechooser.beans.DateChooserCombo jTransDate;
    private javax.swing.JTextField jTransDescr;
    private javax.swing.JTextField jTransDisc;
    private javax.swing.JComboBox<String> jTransType;
    private javax.swing.JTextField jTransValue;
    // End of variables declaration//GEN-END:variables
}
